version: 2.1

orbs:
  codacy: codacy/base@6.1.3
  codacy_plugins_test: codacy/plugins-test@1.1.1

jobs:
  unit_test:
    docker:
      - image: cimg/go:1.19.0
    working_directory: ~/workdir
    steps:
      - attach_workspace: 
          at: ~/workdir
      - run:
          name: Run go test
          command: go test

  lint: 
    docker:
      - image: cimg/go:1.19.0
    working_directory: ~/workdir
    steps:
      - attach_workspace: 
          at: ~/workdir
      - run:
          name: Run go revive
          command: |
            go install github.com/mgechev/revive
            revive -exclude docs/multiple-tests/... -exclude test/... ./...
      - run: 
          name: Run golintci
          command: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.3
            golangci-lint run --disable-all -E gofmt .

workflows:
  version: 2
  compile_test_deploy:
    jobs:
      - codacy/checkout_and_version
      - unit_test:
          requires:
            - codacy/checkout_and_version
      - lint:
          requires:
            - codacy/checkout_and_version
      - codacy/shell:
          name: publish_docker_local
          cmd: |
            make docker
            docker save --output docker-image.tar $CIRCLE_PROJECT_REPONAME:latest
          persist_to_workspace: true
          requires:
            - unit_test
      - codacy_plugins_test/run:
          name: plugins_test
          run_multiple_tests: true
          requires:
            - publish_docker_local
      - codacy/publish_docker:
          context: CodacyDocker
          requires:
            - plugins_test
          filters:
            branches:
              only:
                - master
      - codacy/tag_version:
          name: tag_version
          context: CodacyAWS
          requires:
            - codacy/publish_docker
